### ISSUE TITLE
hi bro, please reply me

### ISSUE THREAD

**Issue by PHANPHUOCDINH** [aysecra/Unity_FlappyBirdClone_MVC#1]
i am very happy because you make a game use mvc pattern for unity, but you can continue make a this game but it use mvvm pattern ? please :( :( thank you so much

**Comment by aysecra** [comment]
I'm glad you like this game even though it have rough edges in terms of mvc pattern. I made this game as a bootcamp practice. If I have time, I can fix the deficiencies and continue this game as mvvm pattern.
